version: '3'

services:
  frontend:
    image: frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "8001:8001"

  backend:
    image: backend
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    expose:
      - 8000
    links:
      - database
    depends_on:
      - database
    environment:
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_HOST: ${DB_HOST}
      DB_DATABASE: ${DB_DATABASE}
      DB_PORT: ${DB_PORT}
      APP_HOST: ${APP_HOST}
      APP_PORT: ${APP_PORT}

  database:
    image: postgres:alpine
    build:
      context: .
      dockerfile: database/Dockerfile
    ports:
      - "5434:5432"
    expose:
      - 5432
      - 5434
    volumes:
      - ./database/db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
