version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "8001:8001"

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    expose:
      - 8000
    links:
      - database
    depends_on:
      - database

  database:
    build:
      context: .
      dockerfile: database/Dockerfile
    ports:
      - "5434:5432"
    expose:
      - 5432
      - 5434
    volumes:
      - ./database/db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
